USE [master]
GO

/****** Object:  Database [DB_HOSPITAL]    Script Date: 09/09/2016 00:43:52 ******/
DROP DATABASE [DB_HOSPITAL]
GO

/****** Object:  Database [DB_HOSPITAL]    Script Date: 09/09/2016 00:43:52 ******/
CREATE DATABASE [DB_HOSPITAL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_HOSPITAL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DB_HOSPITAL.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DB_HOSPITAL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DB_HOSPITAL_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DB_HOSPITAL] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_HOSPITAL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_HOSPITAL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_HOSPITAL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_HOSPITAL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_HOSPITAL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_HOSPITAL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_HOSPITAL] SET  MULTI_USER 
GO

ALTER DATABASE [DB_HOSPITAL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_HOSPITAL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_HOSPITAL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_HOSPITAL] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DB_HOSPITAL] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_HOSPITAL] SET  READ_WRITE 
GO

