USE [DB_HOSPITAL]
GO

/*SCHEMA DEDICADO A OBJETOS DE AUDITORIA*/
CREATE SCHEMA [adt]
GO

/*SCHEMA DEDICADO A OBJETOS DE CONFIGURAÇÃO E PERMISSIONAMENTO*/
CREATE SCHEMA [cfg]
GO

/*SCHEMA DEDICADO A OBJETOS DE CADASTRO GERAL*/
CREATE SCHEMA [cad]
GO

/*SCHEMA DEDICADO A OBJETOS DO PROCESSO DE INTERNAÇÃO (UTI) */
CREATE SCHEMA [uti]
GO



